IPTreatmentManagement.Web/Controllers/IPTreatmentPackagesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using AutoMapper;
using IPTreatmentManagement.Models.ApiRepositoryInterface;
using IPTreatmentManagement.Models.Dtos.Response;
using IPTreatmentManagement.Models.OperationalModels;
using IPTreatmentManagement.Web.ExceptionFilters;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Refit;

namespace IPTreatmentManagement.Web.Controllers
{
    [TypeFilter(typeof(ApiCallExceptionFilter))]
    public class IPTreatmentPackagesController : Controller
    {
        private readonly ILogger<IPTreatmentPackagesController> _logger;
        private readonly IIPTreatmentPackageApiRepository _treatmentPackageApiRepository;

        public IPTreatmentPackagesController(ILogger<IPTreatmentPackagesController> logger,
            IIPTreatmentPackageApiRepository treatmentPackageApiRepository)
        {
            _logger = logger;
            _treatmentPackageApiRepository = treatmentPackageApiRepository;
        }
        public async Task<IActionResult> Index()
        {
            var treatmentPackages = await _treatmentPackageApiRepository.GetAll();
            return View(treatmentPackages);
        }

        public async Task<IActionResult> Details(string treatmentPackageName)
        {
            //try
            //{
                var treatmentPackage = await _treatmentPackageApiRepository.GetByPackageName(treatmentPackageName);
                return View(treatmentPackage);
            //}
            //catch(ApiException ex)
            //{
            //    throw;
            //}

            //return StatusCode(StatusCodes.Status500InternalServerError);
        }
    }
}

IPTreatmentManagement.Web/Controllers/TreatmentPlansController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPTreatmentManagement.Models.ApiRepositoryInterface;
using IPTreatmentManagement.Models.Dtos.Request;
using IPTreatmentManagement.Web.ExceptionFilters;

namespace IPTreatmentManagement.Web.Controllers
{
    [TypeFilter(typeof(ApiCallExceptionFilter))]
    public class TreatmentPlansController : Controller
    {
        private readonly ITreatmentPlanApiRepository _treatmentPlanRepository;

        public TreatmentPlansController(ITreatmentPlanApiRepository treatmentPlanRepository)
        {
            _treatmentPlanRepository = treatmentPlanRepository;
        }

        public async Task<IActionResult> Index()
        {
            var treatmentPlans = await _treatmentPlanRepository.GetAll();
            return View(treatmentPlans);
        }

        public async Task<IActionResult> Create(string treatmentPackageName="")
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PatientRequestDTO patient)
        {
            var newTreatmentPlan = await _treatmentPlanRepository.GenerateTreatmentPlan(patient);

            TempData["Message"] = "Treatment Plan Created";

            return RedirectToAction(nameof(Index));
        }
    }
}

IPTreatmentManagement.Web/Views/IPTreatmentPackages/Details.cshtml
@model IPTreatmentManagement.Models.Dtos.Response.IPTreatmentPackageResponseDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>IPTreatmentPackageResponseDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TreatmentPackageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TreatmentPackageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TestDetails)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TestDetails)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AilmentCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AilmentCategory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TreatmentDurationInDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TreatmentDurationInDays)
        </dd>
    </dl>
</div>

IPTreatmentManagement.Web/Views/IPTreatmentPackages/Index.cshtml
@model IEnumerable<IPTreatmentManagement.Models.Dtos.Response.IPTreatmentPackageResponseDto>

@{
    ViewData["Title"] = "IP Treatment Packages";
}

<h1>Treatment Packages</h1>

<table class="table table-bordered table-hover c-datatable">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TreatmentPackageName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TestDetails)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AilmentCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TreatmentDurationInDays)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TreatmentPackageName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TestDetails)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AilmentCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TreatmentDurationInDays)
                </td>
                <td class="d-flex flex-column">
                    @*@Html.ActionLink("Details", "Details", new { treatmentPackageName = item.TreatmentPackageName })*@
                    <a class="btn btn-outline-dark text-left text-nowrap mb-2"
                       asp-controller="IPTreatmentPackages"
                       asp-action="Details"
                       asp-route-treatmentPackageName="@item.TreatmentPackageName">
                        <i class="fab fa-lg fa-audible"></i> Details
                    </a>
                    <a class="btn btn-outline-dark text-left text-nowrap"
                       asp-controller="TreatmentPlans"
                       asp-action="Create"
                       asp-route-treatmentPackageName="@item.TreatmentPackageName">
                        <i class="fas fa-lg fa-user-injured"></i> Add Patient
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>