IPTreatmentManagement.Web/Controllers/ClaimsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPTreatmentManagement.Models.ApiRepositoryInterface;
using IPTreatmentManagement.Models.Dtos.Request;
using IPTreatmentManagement.Web.ExceptionFilters;

namespace IPTreatmentManagement.Web.Controllers
{
    [TypeFilter(typeof(ApiCallExceptionFilter))]
    public class ClaimsController : Controller
    {
        private readonly IClaimsApiRepository _claimsRepository;

        public ClaimsController(IClaimsApiRepository claimsRepository)
        {
            _claimsRepository = claimsRepository;
        }

        public async Task<IActionResult> Index()
        {
            var claims = await _claimsRepository.GetAll();
            return View(claims);
        }

        public async Task<IActionResult> InitiateClaim()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> InitiateClaim(InitiateClaimRequestDto claimRequest)
        {
            var claims = await _claimsRepository.InitiateClaim(claimRequest);

            TempData["Message"] = "Claim Initiation Request received";

            return RedirectToAction(nameof(Index));
        }
    }
}

IPTreatmentManagement.Web/Controllers/InsurerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPTreatmentManagement.Models.ApiRepositoryInterface;
using IPTreatmentManagement.Web.ExceptionFilters;

namespace IPTreatmentManagement.Web.Controllers
{
    [TypeFilter(typeof(ApiCallExceptionFilter))]
    public class InsurerController : Controller
    {
        private readonly IInsurerApiRepository _insurerRepository;

        public InsurerController(IInsurerApiRepository insurerRepository)
        {
            _insurerRepository = insurerRepository;
        }
        public async Task<IActionResult> Index()
        {
            var insurers = await _insurerRepository.GetAll();
            return View(insurers);
        }

        public async Task<IActionResult> Details(string insurerPackageName)
        {
            var insurer = await _insurerRepository.GetInsurerByPackageName(insurerPackageName);
            return View(insurer);
        }
    }
}

IPTreatmentManagement.Web/Controllers/SpecialistController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPTreatmentManagement.Models.ApiRepositoryInterface;
using IPTreatmentManagement.Web.ExceptionFilters;

namespace IPTreatmentManagement.Web.Controllers
{
    [TypeFilter(typeof(ApiCallExceptionFilter))]
    public class SpecialistController : Controller
    {
        private readonly ISpecialistApiRepository _specialistRepository;

        public SpecialistController(ISpecialistApiRepository specialistRepository)
        {
            _specialistRepository = specialistRepository;
        }
        public async Task<IActionResult> Index()
        {
            var specialists = await _specialistRepository.GetAll();
            return View(specialists);
        }
    }
}

IPTreatmentManagement.Web/Controllers/TreatmentPlansController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPTreatmentManagement.Models.ApiRepositoryInterface;
using IPTreatmentManagement.Models.Dtos.Request;
using IPTreatmentManagement.Web.ExceptionFilters;

namespace IPTreatmentManagement.Web.Controllers
{
    [TypeFilter(typeof(ApiCallExceptionFilter))]
    public class TreatmentPlansController : Controller
    {
        private readonly ITreatmentPlanApiRepository _treatmentPlanRepository;

        public TreatmentPlansController(ITreatmentPlanApiRepository treatmentPlanRepository)
        {
            _treatmentPlanRepository = treatmentPlanRepository;
        }

        public async Task<IActionResult> Index()
        {
            var treatmentPlans = await _treatmentPlanRepository.GetAll();
            return View(treatmentPlans);
        }

        public async Task<IActionResult> Create(string treatmentPackageName="")
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PatientRequestDTO patient)
        {
            var newTreatmentPlan = await _treatmentPlanRepository.GenerateTreatmentPlan(patient);

            TempData["Message"] = "Treatment Plan Created";

            return RedirectToAction(nameof(Index));
        }
    }
}

IPTreatmentManagement.Web/Views/Shared/UserErrorView.cshtml
@model IPTreatmentManagement.Models.OperationalModels.ErrorResponseModel

@{
    ViewData["Title"] = "Error";

    var errorName = (IPTreatmentManagement.Models.OperationalModels.ApplicationStatusCodes)Model.ApplicationStatusCode;
}

<h1 class="text-danger">Error</h1>

<div>
    <h4 class="text-danger">@errorName.ToString()</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ErrorId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ErrorId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationStatusCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationStatusCode)
        </dd>
    </dl>
</div>
@if (Model.ErrorDetails.Any())
{
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    Scope
                </th>
                <th>
                    Error Details
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var errorDetail in Model.ErrorDetails)
            {
                <tr>
                    <td>
                        @errorDetail.Key
                    </td>
                    <td>
                        @errorDetail.Value
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

IPTreatmentManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IPTM</title>

    <partial name="_ViewCssPartial" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.2/datatables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Launch"><i class="fab fa-500px"></i> IPTM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="IPTreatmentPackages" asp-action="Index">Treatment Packages |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Specialist" asp-action="Index">Specialists |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Insurer" asp-action="Index">Insurers |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TreatmentPlans" asp-action="Index">Treatment Plans |</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Claims" asp-action="Index">Claims</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
@*<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
    
</div>*@
<div class="container">
    @if (TempData.ContainsKey("Message"))
    {
        <div class="toast" style="position: absolute; top: 30px; right: 30px;" data-delay="10000">
            <div class="toast-header">
                <strong class="mr-auto"><i class="fas fa-lg fa-bell"></i> Notification</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                @TempData["Message"].ToString()
            </div>
        </div>
    }
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - International Patient Treatment Management Portal
    </div>
</footer>

<partial name="_ViewJsPartial"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.2/datatables.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IPTreatmentManagement.Web/Views/Shared/_ViewCssPartial.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/select2/dist/css/select2.css"/>
    <link rel="stylesheet" href="~/lib/ttskch/select2-bootstrap4-theme/dist/select2-bootstrap4.css"/>
    @*<link rel="stylesheet" href="~/lib/datatables.net-bs4/dataTables.bootstrap4.css"/>*@
</environment>

<environment exclude="Development">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
</environment>

IPTreatmentManagement.Web/Views/Shared/_ViewJsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/select2/dist/js/select2.js"></script>
    <script src="~/lib/sweetalert2/dist/sweetalert2.all.js"></script>
    @*<script src="~/lib/datatables.net-bs4/dataTables.bootstrap4.js"></script>*@
</environment>

<environment exclude="Development">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3488a15d99.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</environment>